### ISSUE TITLE
Question on basic usage

### ISSUE THREAD

**Issue by skipkent** [Nthalk/SeleniumJQuery#3]
I'm trying to use this library in a WebDriver project to expose a hidden element using the show() function.  In a browser console, the following jQuery does what I want:

```
$(".hidden").show()
```

I've compiled your sources and put the resulting class files into a jar file, and then put that jar file into my project.

In my code I then instantiate a JavascriptExecutor object and then one of your jQueryFactory objects using the first one as an argument for the second:

```
JavascriptExecutor js = (JavascriptExecutor)driver;
jQueryFactory jq = new jQueryFactory();
jq.setJs(js);
jq.query(".hidden").show();
```

The 4th line above shows the actual command I'm trying to run, but I keep getting a nulPointerException.  My understanding of Java is not deep enough to really understand if I'm implementing this correctly.  

Huge thanks for any hints you can offer!

```
(stacktrace)
java.lang.NullPointerException
    at org.openqa.selenium.io.IOUtils.readFully(IOUtils.java:34)
    at com.anteambulo.SeleniumJQuery.jQueryFactory.ensurejQuery(jQueryFactory.java:142)
    at com.anteambulo.SeleniumJQuery.jQueryFactory.js(jQueryFactory.java:118)
    at com.anteambulo.SeleniumJQuery.jQuery.js(jQuery.java:608)
    at com.anteambulo.SeleniumJQuery.jQuery.jsref(jQuery.java:612)
    at com.anteambulo.SeleniumJQuery.jQuery.init(jQuery.java:518)
    at com.anteambulo.SeleniumJQuery.jQuery.<init>(jQuery.java:83)
    at com.anteambulo.SeleniumJQuery.jQuery.<init>(jQuery.java:55)
    at com.anteambulo.SeleniumJQuery.jQueryFactory.query(jQueryFactory.java:103)
    at com.nutonian.enterprise.tests.data.DataPage_DatasourceCRUD.dataSourceCRUDtest(DataPage_DatasourceCRUD.java:97)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
    at org.testng.TestRunner.privateRun(TestRunner.java:767)
    at org.testng.TestRunner.run(TestRunner.java:617)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
    at org.testng.SuiteRunner.run(SuiteRunner.java:240)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
    at org.testng.TestNG.run(TestNG.java:1057)
    at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
    at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
```

**Comment by Nthalk** [comment]
While 7 years is a bit late, it looks like there's an issue because while you copied the classes, you missed the resource that needs to be loaded: the jquery source file.

If you are still interested, and have upgraded to maven, there's a new version out today that makes this library much better.
